services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file_craft
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    env_file:
      - .env
    depends_on:
      - db
      # - redis  # Uncomment When you need celery 
    restart: always
    networks:
      - file_craft

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - file_craft

  ## NOTE: Uncomment if you need task

  # redis:
    # image: redis:7
    # container_name: redis
    # restart: always
    # ports:
    #   - "6379:6379"

  # celery_worker:
  #   build:
  #     context: .
  #   container_name: celery_worker
  #   command: celery -A worker.celery_app worker --loglevel=info
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env
  #   depends_on:
  #     - fastapi
  #     - redis
  #     - db
  #   restart: always

  # celery_beat:
  #   build:
  #     context: .
  #   container_name: celery_beat
  #   command: celery -A worker.celery_app beat --loglevel=info
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env
  #   depends_on:
  #     - celery_worker
  #   restart: always

  # flower:
  #   image: mher/flower
  #   container_name: flower
  #   command: flower --broker=redis://redis:6379/0
  #   ports:
  #     - "5555:5555"
  #   depends_on:
  #     - redis
  #   restart: always

volumes:
  pg_data:

networks:
  file_craft:
    driver: bridge  

